name: deploy react app
on: push
jobs: 
  deploy-react-app:
   runs-on: ubuntu-latest
   steps:
     - name: clone the repository
       uses: actions/checkout@v4
       
     - name: npm install
       run: npm install
       
     - name: npm run build
       run: npm run build
       
     - name: npm run test
       run: npm run test
